<a href="https://colab.research.google.com/github/engcarlos1/meu-analisador-ppm/blob/main/HydroLab_HI83300.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# ======================================================
# HydroLab
# Sistema Inteligente para Processamento de Dados do HI83300
#
# Autor: Carlos Daniel
# Versão: 0.1
#
# Este notebook foi desenvolvido para automatizar
# a organização dos dados exportados pelo HI83300.
# ======================================================

In [ ]:
# ==========================================================
# BIBLIOTECAS
# ==========================================================

import io
import re
import pandas as pd
import numpy as np

from google.colab import files
from IPython.display import display

In [ ]:
# Configuração do Projeto

In [ ]:
CONFIG = {

    "Projeto": "HydroLab",

    "Versao": "0.1",

    "Autor": "Carlos Daniel",

    "Equipamento": "HI83300"

}

print(CONFIG)

{'Projeto': 'HydroLab', 'Versao': '0.1', 'Autor': 'Carlos Daniel', 'Equipamento': 'HI83300'}

In [ ]:
# Classe HI83300

In [ ]:
class HI83300:

    def __init__(self):

        self.raw = None

        self.metadata = None

        self.results = None

        print("HI83300 inicializado.")

In [ ]:
lab = HI83300()

HI83300 inicializado.

In [ ]:
class HI83300:

    def __init__(self):

        self.raw = None
        self.metadata = None
        self.results = None

        print("HI83300 inicializado.")

    def importar(self):

        print("Selecione o arquivo exportado pelo HI83300")

        uploaded = files.upload()

        arquivo = list(uploaded.keys())[0]

        self.raw = pd.read_excel(

            arquivo,

            header=None,

            dtype=str

        )

        self.raw = self.raw.fillna("")

        print("Arquivo importado com sucesso!")

        print()

        display(self.raw.head())

In [ ]:
class HI83300:

    def __init__(self):

        self.raw = None
        self.metadata = None
        self.results = None

        print("HI83300 inicializado.")

    def importar(self):

        print("Selecione o arquivo exportado pelo HI83300")

        uploaded = files.upload()

        arquivo = list(uploaded.keys())[0]

        self.raw = pd.read_excel(

            arquivo,

            header=None,

            dtype=str

        )

        self.raw = self.raw.fillna("")

        print("Arquivo importado com sucesso!")

        print()

        display(self.raw.head())

In [ ]:
lab = HI83300()

lab.importar()

HI83300 inicializado.
Selecione o arquivo exportado pelo HI83300

Saving DADOS HI83300.xlsx to DADOS HI83300.xlsx
Arquivo importado com sucesso!

                                          0
0                            Modelo,HI83300
1                       N. Série,ACD0649054
2                     ID Instrumento,000000
3                            Firmware,1.18
4  Última CAL Check,Nov 10 2022,01:28:44 PM

In [ ]:
def _extrair_metadados(self):
    print("Extraindo metadados...")
    # Placeholder for actual metadata extraction logic
    # This assumes metadata might be in the first few rows of the raw data
    if self.raw is not None and not self.raw.empty:
        # Taking the first 5 rows as a conceptual example of metadata
        self.metadata = self.raw.iloc[:5, :].copy()
        print("Metadados extraídos com sucesso (placeholder)!")
    else:
        print("Nenhum dado bruto disponível para extrair metadados.")
    if self.metadata is not None:
        display(self.metadata)

# Dynamically attach the method to the HI83300 class
HI83300.extrair_metadados = _extrair_metadados

# Now, call the method
lab.extrair_metadados()

Extraindo metadados...
Metadados extraídos com sucesso (placeholder)!

                                          0
0                            Modelo,HI83300
1                       N. Série,ACD0649054
2                     ID Instrumento,000000
3                            Firmware,1.18
4  Última CAL Check,Nov 10 2022,01:28:44 PM

In [ ]:
def _extrair_resultados(self):
    print("Extraindo resultados...")
    if self.raw is not None and not self.raw.empty:
        # Assuming metadata is in the first few rows (e.g., first 5 rows),
        # and actual results start from row 5 (index 5) onwards.
        # This is a placeholder; actual logic might involve parsing based on keywords.
        self.results = self.raw.iloc[5:, :].copy()
        print("Resultados extraídos com sucesso (placeholder)!")
    else:
        print("Nenhum dado bruto disponível para extrair resultados.")
    if self.results is not None:
        display(self.results.head())

# Dynamically attach the method to the HI83300 class
HI83300.extrair_resultados = _extrair_resultados

# Now, call the method
lab.extrair_resultados()

Extraindo resultados...
Resultados extraídos com sucesso (placeholder)!

                 0
5  420nm: 0.99 abs
6  466nm: 1.00 abs
7  525nm: 1.00 abs
8  575nm: 1.01 abs
9  610nm: 1.00 abs

In [ ]:
def _organizar(self):
    print("Organizando dados...")
    # This is a placeholder for the actual organization logic.
    # It would typically involve combining and cleaning 'metadata' and 'results'.
    if self.metadata is not None and self.results is not None:
        print("Dados organizados com sucesso (placeholder)!")
        # Example: show a combined view, or set self.organized_data
        # self.organized_data = pd.concat([self.metadata, self.results])
        # display(self.organized_data.head())
    else:
        print("Metadados ou resultados não disponíveis para organização.")

# Dynamically attach the method to the HI83300 class
HI83300.organizar = _organizar

# Now, call the method
lab.organizar()

Organizando dados...
Dados organizados com sucesso (placeholder)!

In [ ]:
def _exportar(self):
    print("Exportando dados...")
    # This is a placeholder for the actual export logic.
    # It would typically involve saving self.results or self.organized_data to a file.
    if self.results is not None and not self.results.empty:
        # Example: to_csv or to_excel
        # self.results.to_csv('resultados_exportados.csv', index=False)
        # files.download('resultados_exportados.csv')
        print("Dados exportados com sucesso (placeholder)!")
    else:
        print("Nenhum dado disponível para exportação.")

# Dynamically attach the method to the HI83300 class
HI83300.exportar = _exportar

# Now, call the method
lab.exportar()

Exportando dados...
Dados exportados com sucesso (placeholder)!

In [ ]:
class HI83300:

    def __init__(self):

        self.raw = None
        self.metadata = None
        self.results = None
        self.organizado = None

        print("✅ HydroLab iniciado com sucesso!")

In [ ]:
lab = HI83300()

✅ HydroLab iniciado com sucesso!

In [ ]:
def importar(self):

    print("📂 Selecione o arquivo exportado pelo HI83300")

    uploaded = files.upload()

    arquivo = list(uploaded.keys())[0]

    self.raw = pd.read_excel(
        arquivo,
        header=None,
        dtype=str
    ).fillna("")

    print(f"\n✅ Arquivo carregado: {arquivo}")
    print(f"📊 Linhas: {self.raw.shape[0]}")
    print(f"📊 Colunas: {self.raw.shape[1]}")

    display(self.raw.head())

In [ ]:
HI83300.importar = importar

lab = HI83300()

lab.importar()

✅ HydroLab iniciado com sucesso!
📂 Selecione o arquivo exportado pelo HI83300

Saving DADOS HI83300.xlsx to DADOS HI83300 (1).xlsx

✅ Arquivo carregado: DADOS HI83300 (1).xlsx
📊 Linhas: 20
📊 Colunas: 1

                                          0
0                            Modelo,HI83300
1                       N. Série,ACD0649054
2                     ID Instrumento,000000
3                            Firmware,1.18
4  Última CAL Check,Nov 10 2022,01:28:44 PM

In [ ]:
def _extrair_metadados(self):
    print("Extraindo metadados...")
    # Placeholder for actual metadata extraction logic
    # This assumes metadata might be in the first few rows of the raw data
    if self.raw is not None and not self.raw.empty:
        # Taking the first 5 rows as a conceptual example of metadata
        self.metadata = self.raw.iloc[:5, :].copy()
        print("Metadados extraídos com sucesso (placeholder)!")
    else:
        print("Nenhum dado bruto disponível para extrair metadados.")
    if self.metadata is not None:
        display(self.metadata)

# Dynamically attach the method to the HI83300 class
HI83300.extrair_metadados = _extrair_metadados

lab.extrair_metadados()

Extraindo metadados...
Metadados extraídos com sucesso (placeholder)!

                                          0
0                            Modelo,HI83300
1                       N. Série,ACD0649054
2                     ID Instrumento,000000
3                            Firmware,1.18
4  Última CAL Check,Nov 10 2022,01:28:44 PM

In [ ]:
def _extrair_resultados(self):
    print("Extraindo resultados...")
    if self.raw is not None and not self.raw.empty:
        # Assuming metadata is in the first few rows (e.g., first 5 rows),
        # and actual results start from row 5 (index 5) onwards.
        # This is a placeholder; actual logic might involve parsing based on keywords.
        self.results = self.raw.iloc[5:, :].copy()
        print("Resultados extraídos com sucesso (placeholder)!")
    else:
        print("Nenhum dado bruto disponível para extrair resultados.")
    if self.results is not None:
        display(self.results.head())

# Dynamically attach the method to the HI83300 class
HI83300.extrair_resultados = _extrair_resultados

lab.extrair_resultados()

Extraindo resultados...
Resultados extraídos com sucesso (placeholder)!

                 0
5  420nm: 0.99 abs
6  466nm: 1.00 abs
7  525nm: 1.00 abs
8  575nm: 1.01 abs
9  610nm: 1.00 abs